### ISSUE TITLE
Synchronization issues

### ISSUE THREAD

**Issue by KawaiNeSenpai** [TheKing-OfTime/YandexMusicModClient#1]
When you rewind the timeline, the status does not change

![Untitled (7)](https://github.com/TheKing-OfTime/YandexMusicModClient/assets/60895366/ee189aee-3555-4995-9824-2d00694d9b09)

[YouTube](https://www.youtube.com/watch?v=vYvxBSwMSVA)

**Comment by TheKing-OfTime** [comment]
Thanks for your report. This is a known bug, but unfortunately i have no any ETA when it will be fixed.
This happens because internal app API doesn't emit ON_PLAYER_STATE when user seeks track manually. So to fix this i need to do deep reverse-engineering and remake some parts of the app. So when i do this the bug will be fixed.

**Comment by TheKing-OfTime** [comment]
I managed to implement some changes so the bug will be fixed it the next release.

https://github.com/TheKing-OfTime/YandexMusicModClient/assets/68960526/49617bbb-f362-4c23-a0f7-3369b498efea

**Comment by TheKing-OfTime** [comment]
Fix [released](https://github.com/TheKing-OfTime/YandexMusicModClient/releases/tag/onlyDiscordRPC)
