### ISSUE TITLE
Album Info

### ISSUE THREAD

**Issue by KawaiNeSenpai** [TheKing-OfTime/YandexMusicModClient#2]
When listening to an album that includes 2 or more tracks. 
When you hover over the album picture, "on "Album Name "" is displayed.
I suggest instead of "on" to write "Album".
![image](https://github.com/TheKing-OfTime/YandexMusicModClient/assets/60895366/6baca3b3-2f70-4372-a12c-96c3a79f81bd)

**Comment by TheKing-OfTime** [comment]
It's a deliberate choice. The example was taken from Spotify Rich Presence. So this won't be changed
![image](https://github.com/TheKing-OfTime/YandexMusicModClient/assets/68960526/148867cd-5c3c-42be-be84-e690c0840ca3)

If/When discord allow use Listening activity type, this modification instantly switch to it (Because it already sends type 2 LISTENING. Discord client just ignores it). It will look like this
![image](https://github.com/TheKing-OfTime/YandexMusicModClient/assets/68960526/e5fb752e-0300-48c2-983a-21c93dbd2b61)
